version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: siphera-backend
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - siphera-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3007/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: siphera-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - siphera-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  siphera-network:
    driver: bridge

volumes:
  # Add any persistent volumes here if needed
  # backend-data:
  # frontend-logs: 